---
apiVersion: v1
kind: Service
metadata:
  name: ksql-frontend
spec:
  ports:
  - port: 8080
  clusterIP: None
  selector:
    app: ksql-frontend
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ksql-frontend
spec:
  serviceName: "ksql-frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: ksql-frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ksql-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        image: matsumana/tsujun:0.0.1
        env:
        - name: KSQL_SERVER
          value: http://ksql-server.aca534.svc.cluster.local:8088
