---
apiVersion: v1
kind: Service
metadata:
  name: ksql-server
spec:
  ports:
  - port: 8088
  clusterIP: None
  selector:
    app: ksql-server
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ksql-server
spec:
  serviceName: "ksql-server"
  replicas: 1
  template:
    metadata:
      labels:
        app: ksql-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ksql-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
          protocol: TCP
        image: confluentinc/cp-ksql-server:5.2.1
        env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: kafka-svc.aca534.svc.cluster.local:9092
        - name: KSQL_SCHEMA_REGISTRY_URL
          value: http://schema.aca534.svc.cluster.local:8081
        - name: KSQL_OPTS
          value: "-Dksql.schema.registry.url=http://schema.aca534.svc.cluster.local:8081"
        - name: KSQL_KSQL_SERVICE_ID
          value: confluent_ksql
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
          
          
