apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    service: gobblin
  name: gobblin
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            service: gobblin
        spec:
          restartPolicy: Never
          containers:
          - image: falcowinkler/job-kafka-hdfs:latest
            imagePullPolicy: Always
            name: gobblin
            env:
            - name: KAFKA_BROKERS
              value: kafka-0.kafka-svc.aca534.svc.cluster.local:9092,kafka-1.kafka-svc.aca534.svc.cluster.local:9092
            - name: SCHEMA_REG_URL
              value: http://schema.aca534.svc.cluster.local:8081
            - name: HADOOP_FS_URI
              value: hdfs://namenode-0.namenode.aca534.svc.cluster.local:9000
