apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: burrow
  name: burrow
spec:
  selector:
    matchLabels:
      service: burrow
  template:
    metadata:
      labels:
        service: burrow
    spec:
      containers: 
      - image: falcowinkler/burrow
        env:
        - name: ZOOKEEPER_QUORUM
          value: "[\"zk-0.zk-hs.aca534.svc.cluster.local:2181\",\"zk-1.zk-hs.aca534.svc.cluster.local:2181\"]"
        - name: KAFKA_QUORUM
          value: "[\"kafka-0.kafka-svc.aca534.svc.cluster.local:9092\"]"
        imagePullPolicy: Always
        name: burrow 
        ports:
        - containerPort: 8000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: burrow
  name: burrow
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    service: burrow
  type: ClusterIP
