apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: tweetbird
  name: tweetbird
spec:
  selector:
    matchLabels:
      service: tweetbird
  template:
    metadata:
      labels:
        service: tweetbird
    spec:
      containers: 
      - image: falcowinkler/tweetbird:master
        envFrom:
        - secretRef:
            name: twitter-api-secret
        env: 
        - name: BOOTSTRAP_SERVERS
          value: kafka-0.kafka-svc.aca534.svc.cluster.local:9092,kafka-1.kafka-svc.aca534.svc.cluster.local:9092
        - name: SCHEMA_REGISTRY_URL
          value: schema-registry.aca534.svc.cluster.local
        imagePullPolicy: Always
        name: tweetbird
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: tweetbird
  name: tweetbird
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: tweetbird
  type: ClusterIP
