---
apiVersion: v1
kind: Service
metadata:
  name: schema
  namespace: aca534
spec:
  ports:
  - port: 8081
  clusterIP: None
  selector:
    app: schema-registry
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: registry
  namespace: aca534
spec:
  serviceName: "schema"
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:3.2.0
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zk-cs.aca534.svc.cluster.local
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema.aca534.svc.cluster.local
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        ports:
        - containerPort: 8081