apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: schema-registry
spec:
  selector:
    matchLabels:
      app: schema-registry
  replicas: 2
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:4.0.1
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zk-cs.aca534.svc.cluster.local
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry.aca534.svc.cluster.local
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        ports:
        - containerPort: 8081